Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"


  config.vm.define "nodejsapp_nginx" do |nodejsapp_nginx|
    nodejsapp_nginx.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end

    nodejsapp_nginx.vm.network "private_network", ip: "192.168.63.10"
    nodejsapp_nginx.vm.hostname = 'nodejsapp-nginx'

    nodejsapp_nginx.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH Key"
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDvwDyZc39iCt18TlgUmt6B9SeXwJDMSGNZsNR1mkANbiiUwZWeKtK5MImgbeNSi6HA2rhC5jiJDzwdRqJOFhLbnmVIwvfyaoxPj893QoywpOnUfqtRASS70vDLGAGUYpuVPcy4X3vKO8BnJlsqj+eMHAxJ8dIpJyoMHIks5ZzaKBHKZA2TvMd0v+COX102EHTqvGBkzBdh9BqTHDv2LUaoiwQX76kxv04qAqegKQkuKQzngkPf2jnBKlOPBApZDXWDN1OQUTrvp+IIWNQlfKcJpu1/mwhKeUXLzm1axx+1Tjji8x24X/HAdoznvq4GgaXa5aNcbL5Lbo8sKYbCZzAymIYaR2ocyzO4sHHzruQFlgV0SpUXp7DsxFjKo7U3wDPwT4EbziAEtbXwOofzXlTZ4eQhY1oo5L18mvPmQ1cgHFKgWZQkViuL5FNgQ2fYbMJq3QulcGmAwrypeIJztUjetNy44GMGorZ2lZQtMQdeoqTJUPSh13BbYirPRzhjoOc=' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "nodejsapp_backend_1" do |nodejsapp_backend_1|
    nodejsapp_backend_1.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end

    nodejsapp_backend_1.vm.network "private_network", ip: "192.168.63.11"
    nodejsapp_backend_1.vm.hostname = 'nodejsapp-backend-1'

    nodejsapp_backend_1.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH Key"
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDvwDyZc39iCt18TlgUmt6B9SeXwJDMSGNZsNR1mkANbiiUwZWeKtK5MImgbeNSi6HA2rhC5jiJDzwdRqJOFhLbnmVIwvfyaoxPj893QoywpOnUfqtRASS70vDLGAGUYpuVPcy4X3vKO8BnJlsqj+eMHAxJ8dIpJyoMHIks5ZzaKBHKZA2TvMd0v+COX102EHTqvGBkzBdh9BqTHDv2LUaoiwQX76kxv04qAqegKQkuKQzngkPf2jnBKlOPBApZDXWDN1OQUTrvp+IIWNQlfKcJpu1/mwhKeUXLzm1axx+1Tjji8x24X/HAdoznvq4GgaXa5aNcbL5Lbo8sKYbCZzAymIYaR2ocyzO4sHHzruQFlgV0SpUXp7DsxFjKo7U3wDPwT4EbziAEtbXwOofzXlTZ4eQhY1oo5L18mvPmQ1cgHFKgWZQkViuL5FNgQ2fYbMJq3QulcGmAwrypeIJztUjetNy44GMGorZ2lZQtMQdeoqTJUPSh13BbYirPRzhjoOc=' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end


    
  config.vm.define "nodejsapp_backend_2" do |nodejsapp_backend_2|
    nodejsapp_backend_2.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end

    nodejsapp_backend_2.vm.network "private_network", ip: "192.168.63.12"
    nodejsapp_backend_2.vm.hostname = 'nodejsapp-backend-2'

    nodejsapp_backend_2.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH Key"
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDvwDyZc39iCt18TlgUmt6B9SeXwJDMSGNZsNR1mkANbiiUwZWeKtK5MImgbeNSi6HA2rhC5jiJDzwdRqJOFhLbnmVIwvfyaoxPj893QoywpOnUfqtRASS70vDLGAGUYpuVPcy4X3vKO8BnJlsqj+eMHAxJ8dIpJyoMHIks5ZzaKBHKZA2TvMd0v+COX102EHTqvGBkzBdh9BqTHDv2LUaoiwQX76kxv04qAqegKQkuKQzngkPf2jnBKlOPBApZDXWDN1OQUTrvp+IIWNQlfKcJpu1/mwhKeUXLzm1axx+1Tjji8x24X/HAdoznvq4GgaXa5aNcbL5Lbo8sKYbCZzAymIYaR2ocyzO4sHHzruQFlgV0SpUXp7DsxFjKo7U3wDPwT4EbziAEtbXwOofzXlTZ4eQhY1oo5L18mvPmQ1cgHFKgWZQkViuL5FNgQ2fYbMJq3QulcGmAwrypeIJztUjetNy44GMGorZ2lZQtMQdeoqTJUPSh13BbYirPRzhjoOc=' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end


end
